use jmpsorject;

DROP TABLE IF EXISTS `EVENT_ACTION`;
DROP TABLE IF EXISTS `EVENT`;
DROP TABLE IF EXISTS `ACTION`;
DROP TABLE IF EXISTS `CONFIG`;


CREATE TABLE `EVENT` (
  `ID` int(10)  unsigned NOT NULL auto_increment,
  `TYPE`  varchar(255),
  PRIMARY KEY  (`ID`)
) 


CREATE TABLE `ACTION` (
  `ID` int(10) unsigned NOT NULL auto_increment,
  `TYPE`  varchar(255),
  PRIMARY KEY  (`ID`)
) 


CREATE TABLE `EVENT_ACTION` (
  `EVENT_ID` int(10) unsigned NOT NULL,
  `ACTION_ID` int(10) unsigned NOT NULL,
  PRIMARY KEY  ( `EVENT_ID`,  `ACTION_ID` ),
  KEY `FK_2` (`ACTION_ID`),
  KEY `FK_1` (`EVENT_ID`)
) 



CREATE TABLE `CONFIG` (
  `NAME`  varchar(255),
  `VALUE` varchar(255),
  PRIMARY KEY  (`NAME`)
) 

=============================================

INSERT INTO `EVENT` VALUES (1, 'INFO');
INSERT INTO `EVENT` VALUES (2, 'WARNING');
INSERT INTO `EVENT` VALUES (3, 'EXCEPTION');

INSERT INTO `ACTION` VALUES (1, 'SendMail');
INSERT INTO `ACTION` VALUES (2, 'LogFile');
INSERT INTO `ACTION` VALUES (3, 'LogDB');

INSERT INTO `EVENT_ACTION` VALUES (1, 2);
INSERT INTO `EVENT_ACTION` VALUES (2, 3);
INSERT INTO `EVENT_ACTION` VALUES (3, 3);
INSERT INTO `EVENT_ACTION` VALUES (3, 1);


INSERT INTO `CONFIG` VALUES ('INTERVAL', 9000);